# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      working-directory: ./client
    - run: yarn test:ci
      working-directory: ./client
    - run: yarn lint
      working-directory: ./client
    - name: Upload coverage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: code_coverage
        path: ./client/coverage
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      
      env:
        CI: true
